version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: slack-ask-bot-api
    restart: unless-stopped
    ports:
      - "7777:5000"
    volumes:
      - ./api:/app
    depends_on:
      - db
    env_file:
      - .env
    tty: true
    networks:
      - slack-ask-bot

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: slack-ask-bot-db
    restart: always
    env_file:
      - .env
    ports:
      - "7778:3306"
    volumes:
      - mysql:/var/lib/mysql
    tty: true
    networks:
      - slack-ask-bot

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: slack-ask-bot-phpmyadmin
    restart: always
    ports:
      - "7779:80"
    env_file:
      - .env
    tty: true
    networks:
      - slack-ask-bot

volumes:
  mysql:

networks:
  slack-ask-bot:
    driver: bridge
